<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=<?php echo $encoding; ?>"/>
		<title>Error</title>
		<link rel="shortcut icon" href="./files/images/demoshop/favicon.ico">
		<link rel="stylesheet" type="text/css" href="./files/css/demoshop.css">
		<link rel="stylesheet" type="text/css" href="./files/css/suggest.blockresponse.css">
		
		<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script language="JavaScript" type="text/javascript" src="./files/js/demoshop/demoshop.js"></script>
		<script language="JavaScript" type="text/javascript" src="./files/js/ffsuggest.blockresponse.js"></script>
	</head>
	<body>

		<div id="container" >
			<div id="header">
				<?php include $helper->getTemplate('header'); ?>
			</div>

			<div id="searchboxLine">
				<div id="searchbox">
					<?php include $helper->getTemplate('searchbox'); ?>
				</div>
			</div>

			<div id="content">
				<div id="asnColumn"></div>

				<div id="resultColumn">
					<p id="breadCrumbTrail">
					<?php echo $error; ?>
					</p>
					<div class="clear">&nbsp;</div>
				</div>

				<div id="infoColumn">
				</div>
		 	</div>
		 	<div id="footer">
				<?php include $helper->getTemplate('footer'); ?>
			</div>
		</div>
	</body>
</html>
