<?php
	if (!empty($asn) && $asn->hasPreviewImages()) {
		foreach ($asn AS $group) {
			if ($group->hasPreviewImages()) {
				echo '<div id="asnTop">
						<h3>'.$group->getName().'</h3>';
				$linkCount = 0;
				foreach ($group AS $element) {
					if ($element->isSelected()) {
						continue;
					}
					if ($linkCount < $group->getDetailedLinkCount()) {
						echo '<div class="asnImage">
								<div>
									<a href="'.$element->getUrl().'">
										<img src="'.$element->getPreviewImage().'" alt="" title="'.$element->getLabel().'" onerror="imageNotFound(this)" onload="resizePicture(this, 80, 115)" />
									</a>
								</div>
								<p>
									<a href="'.$element->getUrl().'">
										'.$element->getLabel().' '.$group->getUnit().' <span>('.$element->getMatchCount().')</span>
									</a>
								</p>
							</div>';
						$linkCount++;
					} else {
						if ($linkCount == $group->getDetailedLinkCount()) {
							echo '<p class="selectLine">
									<select onchange="if (this.value != \'\') {document.location.href=this.value;}">
										<option value="">'.($group->count() - $linkCount).' more...</option>';
						}
						echo '<option value="'.$element->getUrl().'">'.$element->getLabel().' '.$group->getUnit().' ('.$element->getMatchCount().')</option>';
						$linkCount++;
					}
				}
				if($linkCount > $group->getDetailedLinkCount()) {
					echo '</select>
					</p>';
				}
				if ($group->count() <= $group->getDetailedLinkCount()){
					echo '<div class="clear"></div>';
				}
				echo '</div>';
				break;
			}
		}
	}
