<?php
    if (!isset($fieldname)) {
        include 'fieldnamesConfig.php';
    }

    $trackingId  = $record->getField($fieldname['trackingId']);
    $masterId    = $record->getField($fieldname['masterId']);
    $articleNr   = $record->getField($fieldname['artNo']);
    $title       = $record->getField($fieldname['title']);
    $price       = $record->getField($fieldname['price']);
    $description = $record->getField($fieldname['description']);
    $imageUrl    = $record->getField($fieldname['imageUrl']);
    $detailUrl   = $record->getField($fieldname['detailUrl']);
    $origPos     = $record->getField("__ORIG_POSITION__");
    $campaign    = $record->getField("__FFCampaign__");
    $instoreAds  = $record->getField("__FFInstoreAds__");
    $searchTerm  = addslashes(strip_tags($searchParameters->getQuery()));
    if (strlen($searchTerm) === 0 && $searchParameters->getSeoPath() && strpos(strrev($searchParameters->getSeoPath()), 'q/') === 0){
        $seoPathLength = strlen($searchParameters->getSeoPath());
        $seoPathWithoutSuffix = substr($searchParameters->getSeoPath(), 0, $seoPathLength-2);
        $searchTerm = substr($seoPathWithoutSuffix, strrpos($seoPathWithoutSuffix, '/')+1);
    }
?>

<div class="productWrap">
    <div class="product">
        <div class="picture">
            <a href="<?php echo $detailUrl; ?>" onclick="javascript:tracking.click(
                        '<?php echo $searchParameters->getChannel(); ?>',
                        '<?php echo $sid; ?>',
                        '<?php echo $trackingId; ?>',
                        '<?php echo $masterId; ?>',
                        '<?php echo $searchTerm; ?>', 
                        '<?php echo $record->getPosition(); ?>',
                        '<?php echo $origPos; ?>',
                        '<?php echo $paging->getCurrentPage()->getPageNumber(); ?>',
                        '<?php echo $productsPerPageOptions->getDefaultOption()->getLabel(); ?>',
                        '<?php echo $campaign; ?>',
                        '<?php echo $instoreAds; ?>');">
                <img valign="top" src="<?php echo $imageUrl; ?>" alt="no picture"
                    title="<?php echo addslashes($title); ?>" onload="resizePicture(this, 120, 170)"
                    onmouseover="TagToTip('descr<?php echo $articleNr; ?>', SHADOW, true)" onmouseout="UnTip()" />
            </a>
        </div>

        <div style="display:none">
            <span id="descr<?php echo $articleNr; ?>" class="hoverDescription">
                <p style="width:200px; font-weight: bold; margin-bottom: 2px;"><?php echo $title; ?></p>
                <p style="width:200px; text-align: right; margin-top: 0;">
                    Art. No.: <?php echo $articleNr; ?>
                </p>
                <p style="width:200px;">
                <?php
                    echo mb_strimwidth($description, 0, 160, '..', 'UTF-8');
                ?>
            </p>
            </span>
        </div>

        <div class="title">
            <a href="<?php echo $detailUrl; ?>" onclick="javascript:tracking.click(
                        '<?php echo $searchParameters->getChannel(); ?>',
                        '<?php echo $sid; ?>',
                        '<?php echo $trackingId; ?>',
                        '<?php echo $masterId; ?>',
                        '<?php echo $searchTerm; ?>', 
                        '<?php echo $record->getPosition(); ?>',
                        '<?php echo $origPos; ?>',
                        '<?php echo $paging->getCurrentPage()->getPageNumber(); ?>',
                        '<?php echo $productsPerPageOptions->getDefaultOption()->getLabel(); ?>',
                        '<?php echo $campaign; ?>',
                        '<?php echo $instoreAds; ?>');">
            <?php
                echo mb_strimwidth($title, 0, 23, '..', 'UTF-8');
            ?>
            </a>
        </div>
        <div class="price"><?php echo $price; ?> &euro;</div>
    </div>
</div>
